### ISSUE TITLE
!reference highlight

### ISSUE THREAD

**Issue by dotmitsu** [Blarc/gitlab-template-lint-plugin#115]
highlight shows an warning in schema validation
```
.build:
  stage: build and upload
  image: foo/bar
  script:
    - echo Hello

01. Unit-tests:
  stage: unit-tests
  image: !reference [.build, image]
  script: 
    - ./gradlew test
```
![изображение](https://user-images.githubusercontent.com/42657211/235898766-2f4af971-c81d-49d2-921d-e1d41e69466b.png)
![изображение](https://user-images.githubusercontent.com/42657211/235898831-317f4004-7c90-4f96-83b0-158943c3245a.png)
