### ISSUE TITLE
Pipeline filtered out by workflow rules

### ISSUE THREAD

**Issue by oberfoerster** [Blarc/gitlab-template-lint-plugin#118]
To prevent duplicate pipelines (in case of Branch-Pipelines vs. MergeRequestPipelines) `workflow:rules` are used (https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines):

```yaml
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
```
Then the gitlab lint api seems to return "Pipeline filtered out by workflow rules" whenever an open merge request exists.

If a rule `- if: '$CI_PIPELINE_SOURCE == "push"'` is added _before_ the one rule with `when: never`, this error does not occur.
But that is exactly what should be prevented, because then duplicate pipelines will run, one for `push` and one for `merge_request_event`.

It is unclear, why the plugin's API calls are associated with CI_PIPELINE_SOURCE `push` ...

**Comment by Blarc** [comment]
Plugin just sends the whole gitlab yaml file to the Gitlab Lint API. The result should be the same to copying the whole file's content to the Pipeline editor in Gitlab UI. 

Will need to research a bit more how your example behaves. Thanks for reporting.

**Comment by oberfoerster** [comment]
> Plugin just sends the whole gitlab yaml file to the Gitlab Lint API. The result should be the same to copying the whole file's content to the Pipeline editor in Gitlab UI.
> 
> Will need to research a bit more how your example behaves. Thanks for reporting.

Sadly not, I tried that, same rules, same file content results in no error like the one returned by the Lint API.
I tried the CI LInter ($project -> CI/CD -> Pipelines -> CI lint) _and_ the Pipeline Editor ($project -> CI/CD -> Pipelines -> CI lint) without this Error beeing shown.

NB: One can choose a branch in the Editor _but not_ in the CI lint.

Cheers and thank you for looking into it.

**Comment by Blarc** [comment]
I've tried this myself and I've found out that the problem occurs when parameter `dry_run` is set to `true` when calling [Gitlab lint API](https://docs.gitlab.com/ee/api/lint.html).

However, we can't set `dry_run` to `true` and thus enabling [pipeline creation simulation](https://docs.gitlab.com/ee/ci/lint.html#simulate-a-pipeline), because pipeline creation simulation always runs on **default** branch. This would break linting of included yaml files that might have been added or changed. Example, linting the following file:
```yaml
include:
  local: '.test.yml' # this file is new on current branch

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

hello_world:
  script:
    - echo "Hello World!"
```

returns:
```json
{
   "valid":false,
   "errors":[
      "Local file `.test.yml` does not exist!"
   ],
   "warnings":[
      
   ],
   "merged_yaml":null,
   "includes":null
}
```
(source: https://gitlab.com/Blarc/playground)

There is an issue requesting support for running pipeline simulation on tags and non-default branches open [here](https://gitlab.com/groups/gitlab-org/-/epics/6498).


---
There are some things we could do though:
- add a setting and let the user decide if he wants to run the linting with pipeline simulation
- ignore this error (I haven't tested this thoroughly, but I think other errors are shown before `Pipeline filtered out by workflow rules`, which still makes the plugin useful even if we just ignore this error)
- add additional explanation to the error
- add a button to the error to ignore it after it happens

Would love to hear your opinion on this @oberfoerster. Which of the suggested functionalities do you think would be useful? Do you have any other suggestions? :pray:
